{% set name = "multidict" %}
{% set version = "4.7.6" %}
{% set sha256 = "fbb77a75e529021e7c4a8d4e823d88ef4d23674a202be4f5addffc72cbb91430" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - pip
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - py.test tests

about:
  home: http://github.com/aio-libs/multidict
  license: Apache 2.0
  license_file: LICENSE
  summary: multidict implementation

  description: |
    Multidicts are useful for working with HTTP headers, URL query args etc.
  doc_url: http://multidict.readthedocs.io/
  dev_url: http://github.com/aio-libs/multidict

extra:
  recipe-maintainers:
    - sodre
    - kszucs
