{% set version = "6.1.0" %}

package:
  name: multidict
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/multidict/multidict-{{ version }}.tar.gz
  sha256: 22ae2ebf9b0c69d206c003e2f6a914ea33f0a932d4aa16f236afc049d9958f4a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - python
    - pip
    - setuptools >=40
  run:
    - python
    - typing-extensions  # [py<311]

test:
  source_files:
    - tests
  requires:
    - pytest
    - pip
  commands:
    - py.test tests --no-c-extensions  # [python_impl != "cpython"]
    - py.test tests --c-extensions     # [python_impl == "cypthon"]
    - pip check

about:
  home: http://github.com/aio-libs/multidict
  license: Apache-2.0
  license_file: LICENSE
  summary: multidict implementation

  description: |
    Multidicts are useful for working with HTTP headers, URL query args etc.
  doc_url: http://multidict.readthedocs.io/
  dev_url: http://github.com/aio-libs/multidict

extra:
  recipe-maintainers:
    - sodre
    - kszucs
    - xhochy
