{% set version = "6.1.0" %}

package:
  name: multidict
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/multidict/multidict-{{ version }}.tar.gz
  sha256: 22ae2ebf9b0c69d206c003e2f6a914ea33f0a932d4aa16f236afc049d9958f4a

build:
  number: 2
  noarch: python   # [use_noarch]
  track_features:
    - multidict_no_compile  # [use_noarch]
  script:
    - export MULTIDICT_NO_EXTENSIONS=1   # [use_noarch]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform and not use_noarch]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - python {{ python_min }}  # [use_noarch]
    - python {{ python_min }}  # [not use_noarch]
    - pip
    - setuptools >=40
  run:
    - python >={{ python_min }}  # [use_noarch]
    - python >={{ python_min }}  # [not use_noarch]
    - typing-extensions  # [py<311 or use_noarch]

test:
  source_files:
    - tests
  requires:
    - pytest
    - pip
    - python {{ python_min }}
  commands:
    - py.test tests --no-c-extensions  # [use_noarch]
    - py.test tests --c-extensions     # [not use_noarch]
    - pip check

about:
  home: http://github.com/aio-libs/multidict
  license: Apache-2.0
  license_file: LICENSE
  summary: multidict implementation

  description: |
    Multidicts are useful for working with HTTP headers, URL query args etc.
  doc_url: http://multidict.readthedocs.io/
  dev_url: http://github.com/aio-libs/multidict

extra:
  recipe-maintainers:
    - sodre
    - kszucs
    - xhochy
