appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bGvGBdLeFkM1vv6+y0QcDe52FiUnbkURKDcPXPvLYE8jp4bpXeUwG6mbd1GYvKJIIxQgQimofExBBSI8tJTzDir8gDENf68nPn9Nkgm3A3kor7/u4oXb0diNTyAbve+C0bZwdgNc7Ny4ayUC9w8eEEiA8ia6IEIoNEKJG8dDl7sc+bo1luyksS2mrWpIBE1OCHjIaHf6VZVBHKAc8f38uspMx+IoQX6RACfqjUk7Gg5pN4+nzfKO6E/TkGyLMkErrIAV7GFh+dVz+2ORzTCdfwK2iYZUh0gxgZrcGm2OF0lJEWt1zmFgF3osvLO7ffgumKB+AMnyzeVpT5emWV03Ih0QI7sW2PLlD7efucQL6yhO6LFfMRbfIwbHlybU8B2rTxGj2laMUmyjXVGxvCxQGXlqD2jTrJ8/Q8tk2VAOVfw5p2xc32aGc6Mlm1QnGwy7vSnZpTaAkFWCodkViTzokZboasv6nwU1QSeyIN5oLHb4ParMcwm5OZLoWuB0FZC+Al0Abq+QJs/zzVE05xD+YTEsvY3lXj8cR5kN5k3neZkboiuUhlVYVMnb8xVeDEaLMoBt6NyHJXptvLC6d5eIJ16gut8FVEepcW85w/u9ZefM3bQ1hjZvdcS/TCkdjJQkz0DQ2ITn2VO6EcPieAgljDsA33MWW3YNgPDX1NnKG3A=}
